### sign up
POST http://localhost:3000/api/user/signup
Content-Type: application/json

{
    "fullname":"Mansi Gabani",
    "email":"mansigabani231@gamil.com",
    "password":"Mansi123"
}

### sign in
POST http://localhost:3000/api/user/signin
Content-Type: application/json

{
    "email":"mansigabani@gamil.com",
    "password":"123456"
}

### get upload url
POST http://localhost:3000/api/get-upload-url
Content-Type: application/json

{
   "img":"image to upload"
}

### create blog - post method
POST http://localhost:3000/api/blog/create-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWZhZDVlYzA1ZDYzMmRhNDYxMGFmNiIsImlhdCI6MTcwNTU1MTM1MCwiZXhwIjoxNzA4MTQzMzUwfQ._G1w0Rx9yWR95FRzvKDLwu8kHijiiSh5iHFcU2oCyuU


{
   "title":"image to upload"
}