### sign up
POST http://localhost:3000/api/user/signup
Content-Type: application/json

{
    "fullname":"Mansi Gabani",
    "email":"mansigabani231@gamil.com",
    "password":"Mansi123"
}

### sign in
POST http://localhost:3000/api/user/signin
Content-Type: application/json

{
    "email":"mansigabani@gamil.com",
    "password":"123456"
}

### get upload url
GET  http://localhost:3000/api/get-upload-url
