### sign up
POST http://localhost:3000/api/user/signup
Content-Type: application/json

{
    "fullname":"Mansi Gabani",
    "email":"mansigabani231@gamil.com",
    "password":"Mansi123"
}

### sign in
POST http://localhost:3000/api/user/signin
Content-Type: application/json

{
    "email":"mansigabani@gamil.com",
    "password":"123456"
}

### get upload url
POST http://localhost:3000/api/get-upload-url
Content-Type: application/json

{
   "img":"image to upload"
}

### create blog - post method
POST http://localhost:3000/api/blog/create-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YWE1M2QzYjBiN2VjZjZhNjgyNzc0ZCIsImlhdCI6MTcwNTcyNDQ5MCwiZXhwIjoxNzA4MzE2NDkwfQ.eyp32uRH8T9NNADSGO5kcZVVgBLRRUTeW6iqp8jlQbM

{
   "title":"image to upload"
}

### get blogs
GET  http://localhost:3000/api/blog/latest-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YWE1M2QzYjBiN2VjZjZhNjgyNzc0ZCIsImlhdCI6MTcwNTcyNDQ5MCwiZXhwIjoxNzA4MzE2NDkwfQ.eyp32uRH8T9NNADSGO5kcZVVgBLRRUTeW6iqp8jlQbM

### get category wise  search-blogs - post method
POST http://localhost:3000/api/blog/search-blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YWE1M2QzYjBiN2VjZjZhNjgyNzc0ZCIsImlhdCI6MTcwNTcyNDQ5MCwiZXhwIjoxNzA4MzE2NDkwfQ.eyp32uRH8T9NNADSGO5kcZVVgBLRRUTeW6iqp8jlQbM

{
   "tag":"space"
}

### get users by serach - post method
POST http://localhost:3000/api/blog/search-users
Content-Type: application/json

{
   "query":"sarika"
}

### get user profile - get method
POST http://localhost:3000/api/blog/get-profile
Content-Type: application/json

{
   "username":"sarikagabani"
}